### ISSUE TITLE
Compare with ngFocus, ngBlur, angular-ui, etc.

### ISSUE THREAD

**Issue by spl** [shaungrady/angular-window-events#1]
Can you compare/contrast this library with using [`ngFocus`](https://docs.angularjs.org/api/ng/directive/ngFocus), [`ngBlur`](https://docs.angularjs.org/api/ng/directive/ngBlur), the `angular-ui`/[`ui-utils`](http://angular-ui.github.io/ui-utils/) `ui-event`, and possibly others? If you put this in your README, that might help others besides myself.

In my case, I want to listen to window focus and blur events. I'm a relative novice at JavaScript, and I don't understand how or if the above can be used for the window events since they involve adding an attribute to an element. But I can read your code clearly enough and see how it works.

Lastly, you may want to mention that your library is a substitute for angular/angular.js#3276.

**Comment by shaungrady** [comment]
@spl, sorry for the (lengthy) delay in replying to you. This module isn't a directive, as `ngFocus` and `ngBlur` are—those are bound to specific DOM elements. This module allows handling of blur/focus/hide/show of the browser window. These events can be handled inside of a controller, just as `ngFocus`, but it is not bound to an element on the page. No element attributes are required. Instead, simply declare this module as a dependency in your app, then, in the controller that you want to handle the event in, simply...

```javascript
$scope.$on('$windowFocus', function(broadcastEvent, browserEvent) {
  // The window is was just focused.
});
```
