### ISSUE TITLE
Update to latest angular

### ISSUE THREAD

**Issue by matthieusieben** [shaungrady/angular-window-events#27]
Please allow angular 1.7 as peerDependency

**Comment by matthieusieben** [comment]
Wow that was fast, I guess it will be on npm any minute now!

Thanks for beeing so responsive!

**Comment by shaungrady** [comment]
Yup, just published to npm. 👍

**Comment by shaungrady** [comment]
Feel like trying out a rewrite? Version `1.1.0` should be on npm soon. Added a service that tracks the window state. Check out the [README.md](https://github.com/shaungrady/angular-window-events/blob/master/README.md).

Shouldn't break anything. The broadcast stuff is still there and functions the way it always has.
