### ISSUE TITLE
bower install pointing to different repo

### ISSUE THREAD

**Issue by dreadjr** [shaungrady/angular-window-events#3]
`bower install angular-window-events`

produces

ECMDERR Failed to execute "git ls-remote --tags --heads git://github.com/vlio20/angular-window-events.git", exit code of #128 fatal: remote error:    Repository not found.

**Comment by shaungrady** [comment]
@vlio20 would you mind unregistering your `angular-window-events` package with Bower so that I might  use it?

**Comment by desandro** [comment]
I've unregistered `angular-window-events` from the Bower registry, so you can re-register it to the appropriate URL. Thanks for using bower!

**Comment by shaungrady** [comment]
Registered! Thank you @desandro! My apologies for taking so long to get this on Bower.
