### ISSUE TITLE
peerDependencies warning about missing webpack

### ISSUE THREAD

**Issue by matthieusieben** [shaungrady/angular-window-events#31]
Installing v1.1.2 causes the following error:

```
npm WARN babel-loader@6.2.10 requires a peer of webpack@1 || 2 || ^2.1.0-beta || ^2.2.0-rc but none was installed.
```

I do not use babel or webpack (i use rollupjs).

**Comment by shaungrady** [comment]
`1.1.3` has been published with the fix. Thanks for catching these and writing issues—much appreciated 👍
