### ISSUE TITLE
jsnext:main

### ISSUE THREAD

**Issue by matthieusieben** [shaungrady/angular-window-events#32]
Now that the code is written in es6, could you add `jsnext:main` to the package.json, so we can include the es6 version and not the transpiled one ?

http://shuheikagawa.com/blog/2017/01/05/main-jsnext-main-and-module/

**Comment by matthieusieben** [comment]
For this to work, you will need to also publish the `src` folder to npm (of course).

**Comment by shaungrady** [comment]
👍 Sure thing

**Comment by shaungrady** [comment]
Reading that article, it looks like I'll have to create another bundle for `jsnext:main` that doesn't use any ES6 features except `import` and `export`. Not as easy as just pointing to `src/` as I use a lot more features than just those.

**Comment by matthieusieben** [comment]
Well;, could at least have `module` for now.

**Comment by shaungrady** [comment]
Published in `1.1.4`
