### ISSUE TITLE
1.1.2 breaks previous build

### ISSUE THREAD

**Issue by matthieusieben** [shaungrady/angular-window-events#33]
In 1.0.1 you exposed the module using `module.export = angular.module().name` now, it is exported as `exports"window-events" = /* webpack stuff */`. The 1.0 way was the right one according to me.

This breaks compatibility and does not comply with semver.

**Comment by shaungrady** [comment]
Good catch, thanks!

**Comment by shaungrady** [comment]
`1.1.3` has been published with the fix.
